
name: flutter_app

description: Fuel App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.0.0
  geolocator: ^10.0.0
  flutter_map: ^6.0.0
  latlong2: ^0.9.0

flutter:
  uses-material-design: true
